---
# chocomilk vars

# Package Changelog
changelog: "https://release-monitoring.org/api/v2/projects/?name=Wazuh%20Agent%20Windows"
changelog_format: json

# Regex for Version
version: "{{ register_changelog.json['items'][0].stable_versions[0] }}"

# Download URL
url: "https://packages.wazuh.com/4.x/windows/wazuh-agent-{{ version }}-1.msi"

searchreplace:
  "tools/chocolateyinstall.ps1":
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)('.*')
      replace: "$urlPackage = '{{ url }}'"
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: "$checksumPackage = '{{ file_hash }}'"

# readme to description
readme:
  start: 6
  end: 39

# deploy
deploy:
  - provider: chocolatey
    repository: "https://push.chocolatey.org/"
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: chocolatey
    repository: "https://nuget.itigo.tech/upload"
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.wazuh-agent.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://chat.open-circle.ch'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'notification-chocolatey'
